App strings reworked
BrightDV/BoxBox pull request #34
Opened 2022-12-04 04:01 UTC by comradekingu

2022-12-04 15:54 UTC, BrightDV requested changes
Thanks for the PR! Only a small request from my side.

2022-12-04 15:54 UTC, BrightDV commented on lib/l10n/app_en.arb
> -    "freePracticeThree": "Free Practice 3",
Better to keep it to Free Practice FP3

2022-12-04 15:57 UTC, sinfullad commented on lib/l10n/app_en.arb
> +    "freePracticeThree": "Final practice FP3",
the Prix' of the Grand Prix' entered confused me a bit too

we should just follow how F1 says it as Grands Prix entered

2023-02-19 11:04 UTC, BrightDV commented
I finally made a commit on my side with my suggestions and added you as a co-author.
Thanks for PR!

2023-02-19 11:04 UTC, closed without merging